spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rentacardb
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
